### ISSUE TITLE
Fresh Install Fails to Reload Tables / Configuration

### ISSUE THREAD

**Issue by eby** [trombik/ansible-role-opensmtpd#37]
##### ISSUE TYPE

 - Bug Report

##### ROLE VERSION

```
1.4.0 and git master
```

##### CONFIGURATION

Basic config with a file table variable and a smtpd.conf that uses it. I can pass on an larger example if isn't easy to reproduce.

##### OS / ENVIRONMENT

Ubuntu Bionic 64bit via Vagrant (ubuntu/bionic64)
##### SUMMARY

On a fresh ubuntu install, when the package is installed it starts the daemon with the default config. This role then changes the config and adds tables but doesn't restart the daemon (just make sure it is started). As such, when the smtpctl is done for table refresh it errors out as the running-config doesn't have those tables configured.

Restarting the daemon works fine and subsequent runs after that changing config also works as long as those tables previously existed.

I'm not sure what the best solution to this is so haven't sent a PR. I don't see a reload config option in smtpctl. Might be that if a table is created a service restart is needed but not sure what the best checks are. 

##### STEPS TO REPRODUCE

1. Fresh Ubuntu Install
2. Config that creates a table and uses it in config
3. Run the role

```
"msg": "non-zero return code"

ubuntu-bionic python3[3787]: ansible-command Invoked with _raw_params=smtpctl update table sources _uses_shell=False warn=True chdir=None executable=None creates=None removes=None stdin=None
ubuntu-bionic smtpd[2783]: warn: Lookup table not found: "sources"
```

##### EXPECTED RESULTS

- It reloads the configuration on first run
##### ACTUAL RESULTS

- It errors out

**Comment by trombik** [comment]
the following code should restart the daemon at the initial play.

https://github.com/trombik/ansible-role-opensmtpd/blob/master/tasks/main.yml#L128

the test on ubuntu 16.04 shows that the handler indeed restarted the daemon.

```
       RUNNING HANDLER [ansible-role-opensmtpd : Restart opensmtpd] *******************
       changed: [localhost] => {"changed": true, "name": "opensmtpd", "state": "started", "status": {"ActiveEnterTimestamp": "Wed 2018-05-16 09:14:00 UTC", "ActiveEnterTimestampMonotonic": "167616653", ...
```

after the initial play, the daemon accepts a message to a virtual user.
 
```
May 16 09:33:59 ubuntu smtpd[2193]: smtp-in: session 9570eee511335e58: connection from host localhost [IPv6:::1] established
May 16 09:35:04 ubuntu smtpd[2193]: smtp-in: session 9570eee511335e58: msgid=8a0ecbdc, status=Ok, from=<foo@example.org>, to=<postmaster@example.org>, size=249, ndest=1, proto=SMTP
May 16 09:35:04 ubuntu smtpd[2193]: delivery: Ok for 8a0ecbdca5f81802: from=<foo@example.org>, to=<john@example.org>, rcpt=<postmaster@example.org>, user=vmail, method=maildir, delay=23s, stat=Delivered
May 16 09:35:07 ubuntu smtpd[2193]: smtp-in: session 9570eee511335e58: connection from host localhost [IPv6:::1] closed (client sent QUIT)
```

this could have been a failure if the daemon had not been restarted.

i need the raw log output from ansible, the version of the package, and the full configuration for further investigation.

**Comment by eby** [comment]
```
OpenSMTPd version: 6.0.3p1-1build1
Extras version: 5.7.1-3.1build1
```

Notifies are ran at the end so the restart doesn't happen until after it tries to notify the daemon of table changes. 

I guess one option would be to `meta: flush_handlers` after that task. Another option would be to register something when the config is changed and don't do the table reload if the daemon is going to be restarted anyways.

I'll get some log output for you but here is the order:

```
TASK [trombik.opensmtpd : Create smtpd.conf(5)] *************************************************************************************************************
changed: [testing]

TASK [trombik.opensmtpd : Start opensmtpd] ******************************************************************************************************************
ok: [testing]

TASK [trombik.opensmtpd : Notify the daemon when file tables has been updated]
```

**Comment by trombik** [comment]
haven't investigated further, but i think, the issue happens on ubuntu 18.04 while not on 16.04. to reproduce the issue, i need to build and release ubuntu 18.04 release VM first.

**Comment by trombik** [comment]
the role itself has no issue with ubuntu 18.04. however, it fails to start `smtpd(8)` when `opensmtpd-extra` package has mismatched API version.

https://packages.ubuntu.com/xenial/mail/opensmtpd-extras

you have two choices: remove `opensmtpd-extra`, or wait for newer `opensmtpd-extra` package.

**Comment by trombik** [comment]
when the versions match, but you have still issues, please create another issue.

**Comment by trombik** [comment]
version 1.6.0 has been released. please give it a try.

**Comment by eby** [comment]
Thanks. Tested out the 1.6.0 and it works perfectly on a fresh Ubuntu Bionic VM. Thanks again.
